# Generated by Django 6.0.6 on 2026-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
