# Generated by Django 6.0.6 on 2026-06-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_isbn_livro_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
