# Generated by Django 6.0.6 on 2026-06-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('FICCAO', 'Ficção'), ('ROMANCE', 'Romance'), ('TECNICO', 'Técnico'), ('BIOGRAFIA', 'Biografia'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
