# Generated by Django 6.0.6 on 2026-06-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livro_categoria_alter_livro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='emprestado_para',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
